### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by mamantoha** [LeChatErrant/crystalFTP#4]
Hi. Thanks for the great shard.

I have some suggestions.

* Use snake_case for naming files, e.g.`crystal_ftp.cr` instead of `CrystalFTP.cr`
* Format code with `crystal tool format`

**Comment by spuyet** [comment]
I've also a suggestion about naming :smile: 

Why don't you call this shard `ftp` instead of `CrystalFTP` ? It sounds like more natural to me.

**Comment by LeChatErrant** [comment]
Haha thanks guys! :)
 I'm going to change the naming convention, actually crystal documentation support the snake_case convention for naming files so i made a mistake!
And of course, i'll try the `crystal tool format`

For the shard name, i'll thinks about it... Should the shard name be in snake_case or CamelCase?

Thanks again for your advices ;)

**Comment by mamantoha** [comment]
I prefer `snake_case` for shard name.  `ftp` or `ftpd` will be fine. But it's up to you 😄 .

**Comment by LeChatErrant** [comment]
changed! ;)

**Comment by mamantoha** [comment]
Nice  🎉! Closed.
